apiVersion : apps/v1
kind: Deployment
metadata:
  name: fastapi-webrtc
  labels:
    app: fastapi-webrtc
spec:
  selector:
    matchLabels:
      app: fastapi-webrtc
  template:
    metadata:
      labels:
        app: fastapi-webrtc
    spec:
      containers:
        - name: webrtc-fastapi-golang
          image: webrtc-fastapi-golang-webrtc_fastapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          command:
            - "uvicorn"
          args:
            - "src.app:app"
            - "--host=0.0.0.0"
            - "--port=8000"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-webrtc-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-webrtc
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80