apiVersion : apps/v1
kind: Deployment
metadata:
  name: golang-websocket
  labels:
    app: golang-websocket
spec:
  selector:
    matchLabels:
      app: golang-websocket
  template:
    metadata:
      labels:
        app: golang-websocket
    spec:
      containers:
        - name: webrtc-fastapi-golang
          image: webrtc-fastapi-golang-websocket_chat_golang:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: golang-websocket-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang-websocket
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80