apiVersion: v1
kind: Service
metadata:
  name: golang-websocket
  labels:
    app: golang-websocket
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: golang-websocket
  selector:
    app: golang-websocket