apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: yourhost.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs
                port:
                  number: 8080

          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: fastapi-webrtc
                port:
                  number: 8000

          - path: /api/v2
            pathType: Prefix
            backend:
              service:
                name: golang-websocket
                port:
                  number: 8088
